### ISSUE TITLE
[Suggestion] Emblem of Heroism and etc

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/mod-emblem-transfer#10]
Would be nice to add options for Emblem of Heroism, Valor and Conquest cause a lot of players using AC as progressive server / realms.

Other than that, everything works great.

**Comment by pangolp** [comment]
That's a good idea.

**Comment by Valoriaz** [comment]
Think it can be closed now https://github.com/azerothcore/mod-emblem-transfer/pull/27
