### ISSUE TITLE
NPC got noch gossip - serverstart shows Errormsg

### ISSUE THREAD

**Issue by Hangasilly** [azerothcore/mod-emblem-transfer#15]
I installt the mod and put all code in my DB, then made a new build.

Now i got the NPC 'Turca' ingame but there is no gossip.
Just for her text I had to add 1 row into the 'gossip_menu' - table (becouse it wasn't written in the SQL-code), but there is also shown an error-msg at serverstartup:

` Script named 'npc_emblem_transfer' is assigned in database, but has no code! `

So why there is no code for her^^?

**Comment by acidmanifesto** [comment]
please apply the sql in the world folder to the world database. just tested fine with me.
