### ISSUE TITLE
Error when inserting in the database

### ISSUE THREAD

**Issue by pangolp** [azerothcore/mod-emblem-transfer#2]
Greetings people. Yesterday I was testing the module, the truth is that the idea is great, but I found a mistake. I tried to transfer emblems to another character and I found that there were no errors, however, when the other person wanted to claim them, he told me that there was no item with id 0, so I went to the database and found the following.

I found by all means, the way to correct it, but I did not find the return really, nose that is failing, evidently the problem is perhaps in the INTO INSERT, but I could not.

On the other hand, I was thinking that it would be interesting to have another table, where before removing the emblems, save the transfer. In case an error like this occurs, know how many emblems were erased from the character.

Because if it happens in an online server, it could be a difficult problem to correct I think. Then it wouldn't be wrong to have a backup of the erased emblems.

I hope the information will help you, I'm sorry I can't help you any more.
<a href="https://subefotos.com/ver/?46d62fdab58d95561f2fb8e3a04bf4d3o.png" target="_blank"><img src="http://thumbs.subefotos.com/46d62fdab58d95561f2fb8e3a04bf4d3o.jpg" /></a>

**Comment by Deku** [comment]
What's your azerothcore hash?

**Comment by Deku** [comment]
Please test again after updating to 63a158a8f67655c74acba24f6fc64116aa5a5827

**Comment by pangolp** [comment]
I'm sorry I never tried it, the problem is that I leave my server a little bit because of population issues.
