### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/mod-emblem-transfer#4]
For some weird reason, i'm unable to install module.

It say that conf.dist can't be found, but it's already there.

https://i.imgur.com/EozyrlZ.png

**Comment by BarbzYHOOL** [comment]
Have you sorted this module out @Knindzagxg ?

Do you use this module too @milestorme ?

**Comment by milestorme** [comment]
I don’t but I’ll look at it tomorrow and fix it 😉
